org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true

minecraft_version=26.2
forge_version=65.0.3

mod_version=2.2.0
maven_group=com.autoreplant
archives_base_name=autoreplant-26.2-forge
mod_id=autoreplant

org.gradle.java.home=C:\\Program Files\\Java\\jdk-25
